apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-food-deployment
  labels:
    app: api-food
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-food
  template:
    metadata:
      labels:
        app: api-food
    spec:
      containers:
      - name: api-food-container
        image: anthony07m/api-food-mao:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=800"

          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: api-food-configmap
                key: NODE_ENV
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-food-secret
                key: DATABASE_URL
          - name: MERCADO_PAGO_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: api-food-secret
                key: MERCADO_PAGO_ACCESS_TOKEN

        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10