name: Enable Auto Merge

on:
  pull_request:
    types: [labeled, opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  enable-auto-merge:
    if: github.event.pull_request.base == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
